### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mdcleir** [karllark/measure_extinction#25]
Hi,

I am pretty sure I saw the updated version of the documentation this morning on:
https://measure-extinction.readthedocs.io/en/latest/calc_extinction.html
i.e. with the plots and the changes I made last week (elx instead of elv). But now, I again see the old version of the documentation. What happened, or what am I doing wrong?

Marjorie

**Comment by karllark** [comment]
Maybe your browser cache needs to be cleared?  I see the updated version.  :-)

**Comment by mdcleir** [comment]
That was indeed the problem. Thanks!
