### ISSUE TITLE
Upper/lower case filenames

### ISSUE THREAD

**Issue by mdecleir** [karllark/measure_extinction#53]
Filenames are not case-sensitive on Macs, but they are on other systems. This causes some of the tests to fail, because some filenames are upper case, while they are expected to be lower case in the code.

**Comment by karllark** [comment]
Related:  https://www.python.org/dev/peps/pep-0235/

**Comment by karllark** [comment]
Did we agree that lowercase was the way to go?  This is causing errors in the tests that I am trying when I'm attempting to address #48.

**Comment by karllark** [comment]
I can do this for the tests/data in the repository today - I want to get the tests running before tomorrow.  This will require changes all the data files (.dat and .fits) you are using for the SpeX work (e.g., extstar_data).  The needed changes really are in the data files.

**Comment by mdecleir** [comment]
Changing the data file names might fix the tests, but the different scripts (for merging, plotting, calculating extinction, etc.) will have to be adjusted accordingly, because maybe upper case is expected in some of the code. I will check tomorrow if everything is still running consistently.

**Comment by karllark** [comment]
Great plan for tomorrow.

I found less to change than I expected as the data is usually read in via the StarData class.  And this takes the filenames from the .dat files.  This is the strength of classes if they are used consistently.  Change in one place, fix everywhere!

**Comment by mdecleir** [comment]
Great! Thanks for fixing this. I will verify tomorrow that everything is still working as it should.

**Comment by mdecleir** [comment]
Should be fully addressed with PR #55 . I am waiting for the tests to see if everything works on other platforms...
