### ISSUE TITLE
Astropy deprecation warning

### ISSUE THREAD

**Issue by mdecleir** [karllark/measure_extinction#58]
When running `plot_ext.py` with the `--alax` flag to normalize the extinction curve to A(lambda)/A(V), an Astropy Deprecation Warning appears.

For example,
`python plot_ext.py HD229238 --alax`
results in:
`WARNING: AstropyDeprecationWarning: Class AxAvToExv defines class attributes ``inputs``.
                This has been deprecated in v4.0 and support will be removed in v4.1.
                Starting with v4.0 classes must define a class attribute ``n_inputs``.
                Please consult the documentation for details.
                 [astropy.modeling.core]`

I do not fully understand this warning and don't know how to fix it.

**Comment by mdecleir** [comment]
Another warning is encountered when using the `--extmodels` flag:

`AstropyDeprecationWarning: Class CCM89 defines class attributes ``inputs``.
                This has been deprecated in v4.0 and support will be removed in v4.1.
                Starting with v4.0 classes must define a class attribute ``n_inputs``.
                Please consult the documentation for details.
                 [astropy.modeling.core]`

**Comment by karllark** [comment]
Are you using the latest dust-extinction package?  Version 0.9 should not generate this warning.

**Comment by mdecleir** [comment]
Aha! I thought `conda update --all` would have done the trick, but it did not. Updating the dust-extinction package indeed fixed these warnings.
