### ISSUE TITLE
Bug in rebinning function of extinction curves

### ISSUE THREAD

**Issue by mdecleir** [karllark/measure_extinction#87]
I found a bug in the code to rebin extinction curves. The current code can be found here:
https://github.com/karllark/measure_extinction/blob/d88e8e8079601cb63fa97041dbac92bf222dc99a/measure_extinction/extdata.py#L23-L31

Because of the -1 in the index of a, you are not taking the mean of all the desired data.
It is easiest to see what happens if you rebin with a factor of 2. Let's say you want to calculate the 5th element of the rebinned array, i.e. i=5, rebin_fac =2.
Then `np.mean(a[i * rebin_fac : ((i + 1) * rebin_fac) - 1])` will calculate the mean of a[10:11]. However this is just 1 element, and not 2, because indexing of arrays is non-inclusive the last element: a[10:11] = a[10]. It is thus simply taking every second element in the array, instead of calculating the mean of 2 elements.
If you rebin with a factor of 3, it is taking the mean of 2 elements and ignoring the 3rd element, etc.

This can be solved by removing the -1, or by using a different way to rebin an array, e.g. with scipy.stats.binned_statistic(). Both methods give the same result for a rebinning factor of 2. If you go to higher rebinning factors, the result is not exactly the same, because of the way the elements are collected into bins. I would argue that the scipy method is the more accurate one, because of the way it deals with bin edges.

**Comment by karllark** [comment]
Good catch!  Makes sense.  The origin is that the IDL and python behavior in slicing arrays is different, and my brain has still not fully switched.

Do you have the scipy code that would be better?

**Comment by mdecleir** [comment]
Yes, I thought it would be something like that with the slicing.
Here is the scipy code:

```
from scipy import stats
nbins = int(len(a) / rebin_fac)
new_a = stats.binned_statistic(
        np.arange(len(a)),
        a,
        statistic="mean",
        bins=nbins,
    )[0]
```

With this code, you are binning a into nbins and using the mean to calculate the value in every bin. Since we are working with curves (i.e. extinction vs wavelength), there is even a shorter way to rebin both the wavelengths and extinctions in one go:
```
means= stats.binned_statistic(
        waves,
        (waves,exts),
        statistic="mean",
        bins=nbins,
    )[0]
new_waves=means[0]
new_exts=mean[1]
```
