### ISSUE TITLE
Conversion between E(lambda-V) and A(lambda)/A(V) error calculation

### ISSUE THREAD

**Issue by mdecleir** [karllark/measure_extinction#91]
Just putting this here so that we don't forget about the error calculation on A(lambda)/A(V).

**Comment by karllark** [comment]
To give more details - this is to explicitly include the error in A(V) in the A(lambda)/A(V) uncertainties.  It a small change, but formally correct to include it.

**Comment by mdecleir** [comment]
This issue was solved by PR #93 and can be closed.
